(() => {
  'use strict';
  const key='su-cart-v3';
  let lang=localStorage.getItem('su-lang')==='fa'?'fa':'en', catalog=null, quote=null, request=0, busy=false;
  const el=id=>document.getElementById(id), text=(en,fa)=>lang==='fa'?fa:en;
  const money=cents=>new Intl.NumberFormat(lang==='fa'?'fa-IR':'en-US',{style:'currency',currency:'USD'}).format(cents/100);
  let cart={};
  try { const raw=JSON.parse(localStorage.getItem(key)||'null'); if(raw && typeof raw==='object' && !Array.isArray(raw)) cart=raw;
    else {const old=JSON.parse(localStorage.getItem('su-cart-v2')||'[]');const count=Array.isArray(old)?old.filter(x=>typeof x==='string' && x.startsWith('Saffron Healing Oil')).length:0;if(count)cart['saffron-oil-20ml']=Math.min(count,25);}
  } catch {cart={};}
  cart=Object.fromEntries(Object.entries(cart).filter(([id,n])=>/^[a-z0-9][a-z0-9-]{0,79}$/.test(id)&&Number.isInteger(n)&&n>0&&n<=25));
  const save=()=>{localStorage.setItem(key,JSON.stringify(cart));views?.badge();};let views=null;save();
  function addProduct(id){const p=catalog?.products[id];if(!p||p.stock_available<1)return;const before=cart[id]||0;cart[id]=Math.min(25,p.stock_available,before+1);save();views?.notify(cart[id]>before,id);}
  const errors={
    out_of_stock:['The requested quantity is not available. Reduce the quantity or contact us.','تعداد درخواستی موجود نیست. تعداد را کاهش دهید یا با ما تماس بگیرید.'],
    destination_unavailable:['Shipping is not available to this destination.','ارسال به این مقصد در دسترس نیست.'],
    parcel_overweight:['This parcel exceeds the service weight limit. Contact us for a shipping quote.','وزن بسته بیش از حد مجاز است. برای هزینه ارسال با ما تماس بگیرید.'],
    invalid_cart:['Please add a product to your order.','لطفاً محصولی به سفارش اضافه کنید.'],
    quote_expired:['Your quote expired. Review the refreshed total and try again.','اعتبار قیمت پایان یافت. مبلغ جدید را بررسی و دوباره تلاش کنید.'],
    payment_setup:['Shipping has been calculated. Card payments are being activated; please contact us to complete your order.','هزینه ارسال محاسبه شد. پرداخت با کارت در حال راه‌اندازی است؛ برای تکمیل سفارش با ما تماس بگیرید.'],
    customer_details:['Please check your contact and delivery details.','لطفاً اطلاعات تماس و نشانی را بررسی کنید.'],
    already_paid:['This order has already been paid.','این سفارش قبلاً پرداخت شده است.'],
    payment_pending:['This payment request is being checked. Please do not start another payment. Contact us if needed.','درخواست پرداخت در حال بررسی است. پرداخت جدید انجام ندهید؛ در صورت نیاز با ما تماس بگیرید.']
  };
  const message=code=>{const pair=errors[code]||['We could not retrieve a confirmed price or payment status. Please try again later.','دریافت قیمت یا وضعیت پرداخت تأییدشده ممکن نیست. لطفاً بعداً دوباره تلاش کنید.'];return text(...pair);};
  async function api(action,body) {const r=await fetch('api/commerce.php?action='+action,{credentials:'same-origin',cache:'no-store',...(body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,csrf:catalog.csrf})}:{})});let data;try{data=await r.json();}catch{throw Error('service_unavailable');}if(!r.ok)throw Error(data.error||'service_unavailable');return data;}
  function localize(){document.documentElement.lang=lang;document.documentElement.dir=lang==='fa'?'rtl':'ltr';document.querySelectorAll('[data-en]').forEach(e=>{if(e.dataset[lang])e.textContent=e.dataset[lang];});}
  function productPrices(){document.querySelectorAll('[data-stock-product]').forEach(e=>{const p=catalog?.products[e.dataset.stockProduct];e.textContent=p&&p.stock_available<1?text('Out of stock','ناموجود'):'';});document.querySelectorAll('[data-buy-product]').forEach(b=>{const p=catalog?.products[b.dataset.buyProduct];b.disabled=!p||p.stock_available<1;});document.querySelectorAll('[data-usd-product]').forEach(e=>{const p=catalog?.products[e.dataset.usdProduct];e.textContent=p?money(p.usd_cents):text('Price temporarily unavailable','قیمت موقتاً در دسترس نیست');});}
  function renderItems(){const target=el('checkout-items');if(!target)return;target.replaceChildren();for(const [id,n] of Object.entries(cart)){const p=catalog.products[id];if(!p)continue;const row=document.createElement('div');row.className='checkout-item';const name=document.createElement('span');name.textContent=(lang==='fa'?p.name_fa:p.name)+' · '+money(p.usd_cents);const qty=document.createElement('input');qty.type='number';qty.min='1';qty.max=String(Math.min(25,p.stock_available));qty.value=n;qty.setAttribute('aria-label',text('Quantity','تعداد'));qty.addEventListener('change',()=>{const v=Number(qty.value);if(!Number.isInteger(v)||v<1||v>Math.min(25,p.stock_available)){qty.value=cart[id];return;}cart[id]=v;save();refreshQuote();});const remove=document.createElement('button');remove.type='button';remove.textContent='×';remove.setAttribute('aria-label',text('Remove product','حذف محصول'));remove.onclick=()=>{delete cart[id];save();renderItems();refreshQuote();};row.append(name,qty,remove);target.append(row);}}
  function line(label,value,total=false){const row=document.createElement('div');row.className='checkout-line'+(total?' checkout-total':'');const a=document.createElement('span'),b=document.createElement('span');a.textContent=label;b.textContent=value;row.append(a,b);return row;}
  function showQuote(){const box=el('checkout-summary');if(!box)return;box.replaceChildren();if(!quote){box.textContent=text('Choose a destination to calculate shipping.','برای محاسبه ارسال، مقصد را انتخاب کنید.');return;}
    const base=Math.round(quote.shipping_base_ils_cents/quote.rate),discount=base-quote.shipping_usd_cents;
    box.append(line(text('Products','محصولات'),money(quote.product_usd_cents)),line(text('ECO POST shipping','ارسال ECO POST'),money(base)),line(text('Shipping discount (₪10)','تخفیف ارسال (۱۰ شِکِل)'),'-'+money(discount)),line(text('Shipping after discount','ارسال پس از تخفیف'),money(quote.shipping_usd_cents)),line(text('Total charged in USD','مبلغ پرداخت به دلار'),money(quote.total_usd_cents),true));
    const info=document.createElement('p');info.textContent=text(`Parcel: ${quote.weight_grams} g. Shipping exchange rate dated ${quote.rate_date}. This quote is valid for 15 minutes.`,`وزن بسته: ${quote.weight_grams} گرم. نرخ تبدیل هزینه ارسال در تاریخ ${quote.rate_date}. اعتبار قیمت: ۱۵ دقیقه.`);box.append(info);
    const tax=document.createElement('p');tax.textContent=text('Shipping covers postage only; import duties or local taxes are not included.','هزینه ارسال فقط شامل پست است؛ عوارض واردات یا مالیات محلی در این مبلغ نیست.');box.append(tax);
    el('checkout-note').textContent=quote.payment_available?'':message(quote.unavailable_reason);el('checkout-pay').disabled=!quote.payment_available||busy;
  }
  async function refreshQuote(){const seq=++request;quote=null;el('checkout-pay').disabled=true;el('checkout-note').textContent='';showQuote();if(!Object.keys(cart).length){el('checkout-status').textContent=message('invalid_cart');return;}const country=el('checkout-country').value;addressRules();el('region-label').hidden=country!=='PT';if(!country)return;el('checkout-status').textContent=text('Calculating shipping…','در حال محاسبه ارسال…');try{const next=await api('quote',{items:cart,country,region:country==='PT'?el('checkout-region').value:''});if(seq!==request)return;quote=next;el('checkout-status').textContent='';showQuote();}catch(e){if(seq===request)el('checkout-status').textContent=message(e.message);}}
  function addressRules(){const country=el('checkout-country').value,form=el('checkout-form');form.elements.state.required=['US','CA','AU'].includes(country);const p=form.elements.postal_code;p.pattern=({US:'[0-9]{5}(-[0-9]{4})?',CA:'[A-Za-z][0-9][A-Za-z] ?[0-9][A-Za-z][0-9]',AU:'[0-9]{4}'})[country]||'.*';p.title=({US:'12345 or 12345-6789',CA:'A1A 1A1',AU:'1234'})[country]||'';}
  function countries(){const select=el('checkout-country');if(!select)return;const current=select.value;select.replaceChildren();const placeholder=new Option(text('Choose a country','کشور را انتخاب کنید'),'');select.add(placeholder);const names=new Intl.DisplayNames([lang],{type:'region'});Object.keys(catalog.countries).map(code=>[code,names.of(code)]).sort((a,b)=>a[1].localeCompare(b[1],lang)).forEach(([code,name])=>select.add(new Option(name,code)));select.value=current;}
  async function init(){document.querySelectorAll('[data-checkout-lang]').forEach(b=>b.onclick=()=>{lang=b.dataset.checkoutLang;localStorage.setItem('su-lang',lang);localize();if(catalog){countries();renderItems();showQuote();views?.render();productPrices();}});
    document.querySelectorAll('.lang-btn').forEach(b=>b.addEventListener('click',()=>{lang=b.dataset.lang;productPrices();views?.render();}));
    document.querySelectorAll('[data-buy-product]').forEach(b=>b.addEventListener('click',()=>{addProduct(b.dataset.buyProduct);}));
    localize();views=window.ShopViews?.({text,money,api,getCart:()=>cart,getCatalog:()=>catalog,saveCart:save,addProduct,getLang:()=>lang,message});views?.mount();
    try{catalog=await api('catalog');cart=Object.fromEntries(Object.entries(cart).filter(([id])=>Object.hasOwn(catalog.products,id)));save();productPrices();views?.render();if(!el('checkout-form'))return;countries();renderItems();
      const form=el('checkout-form');let saved={};try{saved=JSON.parse(sessionStorage.getItem('su-delivery')||'{}');}catch{}
      for(const [k,v] of Object.entries(saved)){const f=form.elements.namedItem(k);if(f&&f.type!=='checkbox')f.value=v;}
      el('checkout-country').value=sessionStorage.getItem('su-country')||saved.country||'';el('checkout-region').value=sessionStorage.getItem('su-region')||saved.region||'mainland';
      form.addEventListener('input',()=>{const data=Object.fromEntries(new FormData(form));delete data.consent;sessionStorage.setItem('su-delivery',JSON.stringify(data));});
      const order=new URLSearchParams(location.search).get('order');if(order){el('checkout-content').hidden=true;el('checkout-status').textContent=text('Verifying payment…','در حال بررسی پرداخت…');const result=await api('status',{order});if(result.status==='paid'){sessionStorage.removeItem('su-delivery');}if(result.status==='paid'&&!sessionStorage.getItem('paid-'+order)){const purchased=Object.fromEntries(result.items.map(i=>[i.id,i.quantity]));if(JSON.stringify(cart)===JSON.stringify(purchased)){cart={};save();}sessionStorage.setItem('paid-'+order,'1');}el('checkout-status').textContent=result.status==='paid'?text(`Payment confirmed. Order ${result.reference} · ${money(result.total_usd_cents)}.`,`پرداخت تأیید شد. سفارش ${result.reference} · ${money(result.total_usd_cents)}.`):text('Payment has not been confirmed. If you submitted payment, do not pay again; contact shervinahuniversal@gmail.com.','پرداخت هنوز تأیید نشده است. اگر پرداخت کرده‌اید، دوباره پرداخت نکنید؛ با shervinahuniversal@gmail.com تماس بگیرید.');if(result.status!=='paid'){const retry=document.createElement('button');retry.textContent=text('Check payment again','بررسی دوباره پرداخت');retry.onclick=()=>location.reload();el('checkout-status').append(document.createElement('br'),retry);}if(result.order_url){const a=document.createElement('a');a.href=result.order_url;a.textContent=text('View order status','مشاهده وضعیت سفارش');el('checkout-status').append(document.createElement('br'),a);}return;}
      if(catalog.pending_order){el('checkout-content').hidden=true;el('checkout-status').textContent=message('payment_pending');const a=document.createElement('a');a.href='checkout.html?order='+catalog.pending_order.id;a.textContent=text('Check existing payment','بررسی پرداخت قبلی');el('checkout-status').append(document.createElement('br'),a);if(catalog.pending_order.url){const resume=document.createElement('a');resume.href=catalog.pending_order.url;resume.textContent=text('Return to the same payment page','بازگشت به همان صفحه پرداخت');el('checkout-status').append(document.createElement('br'),resume);}return;}
      showQuote();addressRules();if(el('checkout-country').value)refreshQuote();el('checkout-country').onchange=()=>{sessionStorage.setItem('su-country',el('checkout-country').value);refreshQuote();};el('checkout-region').onchange=refreshQuote;
      el('checkout-form').onsubmit=async e=>{e.preventDefault();if(busy||!quote?.payment_available)return;busy=true;el('checkout-pay').disabled=true;const form=new FormData(e.target);try{const result=await api('checkout',{quote_id:quote.id,consent:form.get('consent')==='on',language:lang,customer:Object.fromEntries(['name','email','phone','address','city','state','postal_code'].map(k=>[k,form.get(k)]))});location.assign(result.url);}catch(err){el('checkout-status').textContent=message(err.message);if(err.message==='quote_expired')await refreshQuote();busy=false;showQuote();}};
    }catch(e){productPrices();if(el('product-content'))el('product-content').textContent=message(e.message);const grid=document.querySelector('.shop-page-grid');if(grid)grid.textContent=message(e.message);if(el('checkout-status'))el('checkout-status').textContent=message(e.message);}
  }
  init();
})();
