<?php
declare(strict_types=1);
session_set_cookie_params(['httponly'=>true,'secure'=>true,'samesite'=>'Strict']);
session_start();
header('X-Frame-Options: DENY');header('X-Content-Type-Options: nosniff');header('Referrer-Policy: no-referrer');header('Cache-Control: no-store');
$configPath=dirname(__DIR__,2).'/private-config.php';
if(!is_file($configPath)){http_response_code(503);exit('הגדרת אזור הניהול עדיין לא הושלמה.');}
$config=require $configPath;
if(isset($_GET['logout'])){session_destroy();header('Location: index.php');exit;}
$error='';
if($_SERVER['REQUEST_METHOD']==='POST'&&isset($_POST['password'])){
 if(password_verify((string)$_POST['password'],(string)$config['admin_password_hash'])){session_regenerate_id(true);$_SESSION['su_admin']=true;$_SESSION['csrf']=bin2hex(random_bytes(24));header('Location: orders.php');exit;}
 $error='הסיסמה שגויה.';
}
if(empty($_SESSION['su_admin'])){?><!doctype html><html lang="he" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>כניסה לניהול | Shervinah</title><style>body{font:16px system-ui;background:#e8c968;margin:0;display:grid;place-items:center;min-height:100vh}form{background:#fff;padding:2rem;max-width:380px;width:calc(100% - 3rem);box-sizing:border-box}input,button{box-sizing:border-box;width:100%;padding:.9rem;margin-top:.7rem;font:inherit}button{background:#111;color:#fff;border:0;cursor:pointer}label{display:block}p[role=alert]{color:#900}</style></head><body><form method="post"><h1>ניהול Shervinah Universal</h1><label>סיסמה<input type="password" name="password" autocomplete="current-password" required></label><button type="submit">כניסה</button><?php if($error):?><p role="alert"><?=htmlspecialchars($error)?></p><?php endif?></form></body></html><?php exit;}
$pdo=new PDO('mysql:host='.$config['db_host'].';dbname='.$config['db_name'].';charset=utf8mb4',$config['db_user'],$config['db_pass'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);
if($_SERVER['REQUEST_METHOD']==='POST'&&isset($_POST['lead_id'],$_POST['status'])){
 if(!hash_equals((string)($_SESSION['csrf']??''),(string)($_POST['csrf']??'')))exit('בקשה לא תקינה.');
 $allowed=['new','contacted','completed'];$status=(string)$_POST['status'];if(in_array($status,$allowed,true)){$stmt=$pdo->prepare('UPDATE su_leads SET status=:status,updated_at=UTC_TIMESTAMP() WHERE id=:id');$stmt->execute(['status'=>$status,'id'=>(int)$_POST['lead_id']]);}header('Location: index.php');exit;
}
$filter=(string)($_GET['type']??'');$allowedTypes=['club','course','collaboration','personal_message','contact'];$sql='SELECT * FROM su_leads';$params=[];if(in_array($filter,$allowedTypes,true)){$sql.=' WHERE form_type=:type';$params['type']=$filter;}$sql.=' ORDER BY created_at DESC LIMIT 250';$stmt=$pdo->prepare($sql);$stmt->execute($params);$leads=$stmt->fetchAll();
$typeLabels=['club'=>'מועדון','course'=>'קורס','collaboration'=>'שיתוף פעולה','personal_message'=>'מסר אישי','contact'=>'צור קשר'];
$statusLabels=['new'=>'חדש','contacted'=>'נוצר קשר','completed'=>'הושלם'];
$fieldLabels=['message'=>'הודעה','subject'=>'נושא','company'=>'חברה','birth_date'=>'תאריך לידה','mother_name'=>'שם האם','language'=>'שפה','marketing_consent'=>'אישור דיוור','service_consent'=>'אישור שירות ופרטיות'];
?><!doctype html><html lang="he" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>פניות | Shervinah</title><link rel="stylesheet" href="admin.css"></head><body><header><strong>Shervinah · ניהול החנות</strong><a href="orders.php">הזמנות</a><a href="products.php">מוצרים ומלאי</a><a href="index.php">פניות</a><a href="email-settings.php">הגדרות מייל</a><a href="?logout=1">יציאה</a></header><main><h1>פניות מהאתר</h1><nav class="filters"><a href="index.php">הכול</a><?php foreach($allowedTypes as $type):?><a href="?type=<?=urlencode($type)?>"><?=htmlspecialchars($typeLabels[$type]??$type)?></a><?php endforeach?></nav><p><?=count($leads)?> פניות מוצגות</p><?php foreach($leads as $lead):$payload=json_decode((string)$lead['payload_json'],true)?:[];?><article><div class="meta"><strong>#<?=intval($lead['id'])?> <?=htmlspecialchars($typeLabels[$lead['form_type']]??$lead['form_type'])?></strong><span><?=htmlspecialchars($lead['created_at'])?> UTC</span><span>סטטוס: <?=htmlspecialchars($statusLabels[$lead['status']]??$lead['status'])?></span></div><dl><dt>שם</dt><dd><?=htmlspecialchars($lead['full_name'])?></dd><dt>אימייל</dt><dd><a href="mailto:<?=htmlspecialchars($lead['email'])?>"><?=htmlspecialchars($lead['email'])?></a></dd><dt>טלפון</dt><dd><?=htmlspecialchars($lead['phone'])?></dd><?php foreach($payload as $key=>$value):if(in_array($key,['email','phone','full_name','first_name'],true))continue;?><dt><?=htmlspecialchars($fieldLabels[$key]??str_replace('_',' ',$key))?></dt><dd><?=htmlspecialchars((string)$value)?></dd><?php endforeach?></dl><form method="post"><input type="hidden" name="csrf" value="<?=htmlspecialchars($_SESSION['csrf'])?>"><input type="hidden" name="lead_id" value="<?=intval($lead['id'])?>"><label>עדכון סטטוס<select name="status"><option value="new" <?=$lead['status']==='new'?'selected':''?>>חדש</option><option value="contacted" <?=$lead['status']==='contacted'?'selected':''?>>נוצר קשר</option><option value="completed" <?=$lead['status']==='completed'?'selected':''?>>הושלם</option></select></label><button type="submit">שמירת סטטוס</button></form></article><?php endforeach?></main></body></html>