<?php
declare(strict_types=1);
session_set_cookie_params(['httponly'=>true,'secure'=>true,'samesite'=>'Strict']);
session_start();
header('X-Frame-Options: DENY');header('X-Content-Type-Options: nosniff');header('Referrer-Policy: no-referrer');header('Cache-Control: no-store');
$configPath=dirname(__DIR__,2).'/private-config.php';
if(!is_file($configPath)){http_response_code(503);exit('Admin setup is not complete.');}
$config=require $configPath;
if(isset($_GET['logout'])){session_destroy();header('Location: index.php');exit;}
$error='';
if($_SERVER['REQUEST_METHOD']==='POST'&&isset($_POST['password'])){
 if(password_verify((string)$_POST['password'],(string)$config['admin_password_hash'])){session_regenerate_id(true);$_SESSION['su_admin']=true;$_SESSION['csrf']=bin2hex(random_bytes(24));header('Location: index.php');exit;}
 $error='Invalid password.';
}
if(empty($_SESSION['su_admin'])){?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Shervinah Admin</title><style>body{font:16px system-ui;background:#e8c968;margin:0;display:grid;place-items:center;min-height:100vh}form{background:#fff;padding:2rem;max-width:380px;width:calc(100% - 3rem)}input,button{box-sizing:border-box;width:100%;padding:.9rem;margin-top:.7rem}button{background:#111;color:#fff;border:0}</style></head><body><form method="post"><h1>Shervinah Admin</h1><label>Password<input type="password" name="password" autocomplete="current-password" required></label><button type="submit">Sign in</button><?php if($error):?><p role="alert"><?=htmlspecialchars($error)?></p><?php endif?></form></body></html><?php exit;}
$pdo=new PDO('mysql:host='.$config['db_host'].';dbname='.$config['db_name'].';charset=utf8mb4',$config['db_user'],$config['db_pass'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);
if($_SERVER['REQUEST_METHOD']==='POST'&&isset($_POST['lead_id'],$_POST['status'])){
 if(!hash_equals((string)($_SESSION['csrf']??''),(string)($_POST['csrf']??'')))exit('Invalid request.');
 $allowed=['new','contacted','completed'];$status=(string)$_POST['status'];if(in_array($status,$allowed,true)){$stmt=$pdo->prepare('UPDATE su_leads SET status=:status,updated_at=UTC_TIMESTAMP() WHERE id=:id');$stmt->execute(['status'=>$status,'id'=>(int)$_POST['lead_id']]);}header('Location: index.php');exit;
}
$filter=(string)($_GET['type']??'');$allowedTypes=['club','course','collaboration','personal_message'];$sql='SELECT * FROM su_leads';$params=[];if(in_array($filter,$allowedTypes,true)){$sql.=' WHERE form_type=:type';$params['type']=$filter;}$sql.=' ORDER BY created_at DESC LIMIT 250';$stmt=$pdo->prepare($sql);$stmt->execute($params);$leads=$stmt->fetchAll();
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Shervinah inquiries</title><style>body{font:15px system-ui;margin:0;background:#f4d67c;color:#111}header{display:flex;gap:1rem;justify-content:space-between;align-items:center;padding:1rem 3vw;background:#111;color:#fff}main{padding:2rem 3vw}.filters{display:flex;gap:.6rem;flex-wrap:wrap;margin-bottom:1rem}.filters a{padding:.55rem .8rem;background:#fff;color:#111;text-decoration:none}article{background:#fff;padding:1rem;margin-bottom:1rem;border-left:6px solid #d82325}.meta{display:flex;gap:1rem;flex-wrap:wrap;color:#555}dl{display:grid;grid-template-columns:minmax(120px,200px) 1fr;gap:.4rem}dt{font-weight:700}dd{margin:0;overflow-wrap:anywhere}button,select{padding:.55rem}a{color:inherit}@media(max-width:600px){dl{grid-template-columns:1fr}}</style></head><body><header><strong>Shervinah Universal inquiries</strong><a href="?logout=1">Sign out</a></header><main><nav class="filters"><a href="index.php">All</a><?php foreach($allowedTypes as $type):?><a href="?type=<?=urlencode($type)?>"><?=htmlspecialchars($type)?></a><?php endforeach?></nav><p><?=count($leads)?> inquiries shown</p><?php foreach($leads as $lead):$payload=json_decode((string)$lead['payload_json'],true)?:[];?><article><div class="meta"><strong>#<?=intval($lead['id'])?> <?=htmlspecialchars($lead['form_type'])?></strong><span><?=htmlspecialchars($lead['created_at'])?> UTC</span><span>Status: <?=htmlspecialchars($lead['status'])?></span></div><dl><dt>Name</dt><dd><?=htmlspecialchars($lead['full_name'])?></dd><dt>Email</dt><dd><a href="mailto:<?=htmlspecialchars($lead['email'])?>"><?=htmlspecialchars($lead['email'])?></a></dd><dt>Phone</dt><dd><?=htmlspecialchars($lead['phone'])?></dd><?php foreach($payload as $key=>$value):if(in_array($key,['email','phone','full_name','first_name'],true))continue;?><dt><?=htmlspecialchars(str_replace('_',' ',$key))?></dt><dd><?=htmlspecialchars((string)$value)?></dd><?php endforeach?></dl><form method="post"><input type="hidden" name="csrf" value="<?=htmlspecialchars($_SESSION['csrf'])?>"><input type="hidden" name="lead_id" value="<?=intval($lead['id'])?>"><select name="status"><option value="new">New</option><option value="contacted">Contacted</option><option value="completed">Completed</option></select><button type="submit">Update status</button></form></article><?php endforeach?></main></body></html>